# Generated by Django 5.0.2 on 2025-05-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_resume_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
