# Generated by Django 5.0.2 on 2025-05-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_resume_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='scoring_status',
            field=models.CharField(choices=[('pending', 'Pending Score'), ('processing', 'Processing'), ('completed', 'Scored'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='use_async',
            field=models.BooleanField(default=False),
        ),
    ]
