version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: resume-screener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-staging_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  # Redis Cache and Message Broker
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-staging_redis_password}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  # Django Backend Application
  web:
    image: ghcr.io/${GITHUB_REPOSITORY:-user/resume-screener}-web:develop
    restart: unless-stopped
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD:-staging_password}@db:5432/resume_screener
      - REDIS_URL=redis://:${REDIS_PASSWORD:-staging_redis_password}@redis:6379/0
      - SECRET_KEY=${SECRET_KEY:-staging-secret-key}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-staging.yourdomain.com,localhost}
      - AI_MICROSERVICE_URL=http://ai-service:8001
      - EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - logs_volume:/app/logs

  # AI Microservice
  ai-service:
    image: ghcr.io/${GITHUB_REPOSITORY:-user/resume-screener}-ai-service:develop
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD:-staging_redis_password}@redis:6379/1
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - ai-service
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  logs_volume:

networks:
  app-network:
    driver: bridge
